<template>
  <div>
    <Header msg="LOG IN" selectedUser="selected-header" />
    <main>
      <section>
        <div id="user_inform" class="layout">
          <div class="title">
            <span class="title">USER INFORMATION</span>
            <button @click="handleClick">LOG OUT</button>
          </div>

          <!-- this data need to generate auto by system -->
          <div id="information">
            <i class="far fa-user-circle icon-user"></i>
            <span style="margin-right: 0.5rem">Name : </span>
            <span>{{ user.displayName }}</span>
            <!-- name must be taken from system when user sign up -->
          </div>
          <div id="information">
            <i class="far fa-envelope-open icon-email"></i>
            <span style="margin-right: 0.5rem;">
              E-mail :
            </span>
            <span>{{ user.email}}</span>
            <!-- id must be generated by system -->
          </div>
          <div id="information">
            <i class="fas fa-id-card icon-email"></i>
            <span style="margin-right: 0.5rem;">
              Customer ID:
            </span>
            <span>{{ user.uid}}</span>
            <!-- id must be generated by system -->
          </div>
        </div>
        <div id="card_payment" class="layout">
          <div class="title">
            <span class="title">CARD & PAYMENT</span>
             <button @click="showCard" v-if="!showAddCard"  class="addcard-btn" >ADD NEW CARD <i class="fas fa-plus-circle"></i></button>
             <button @click="showCard" v-if="showAddCard"  class="addcard-btn" >CLOSE REGISTRATION <i class="fas fa-times-circle"></i></button>
          </div>
         <card-registration v-if="showAddCard" />
          <!-- a user can  have more than one card
          and this div maybe need to loop, and also take data from datbase  -->
          <Card/>
        </div>
        <div id="wishlists" class="layout">
          <div class="title">
            <span class="title">YOUR WISHLISTS</span>
          </div>
          <wish-lists/>
        </div>
      </section>
    </main>
    <Footer />
  </div>
</template>

<script>
import Header from "./Header";
import Footer from "./Footer";
import getUser from '../composables/getUser'
import useLogout from '../composables/useLogout'
import {useRouter} from 'vue-router'
import {watch} from 'vue'
import Card from "../components/Card.vue"
import WishLists from "../components/WishListPage.vue"
import CardRegistration from '../components/CardRegistration.vue';
export default {
  name: "userpage",
  data(){
    return {
      showAddCard : false
    }
  },
  methods:{
    showCard(){
      this.showAddCard = !this.showAddCard
    }
  },
  components: {
    Header,
    Footer,
    Card,
    WishLists,
    CardRegistration
  },
  setup() {
		const {error,logout} = useLogout();
		const {user} = getUser();
		const router = useRouter();

		const handleClick =  async() => {
			await logout()
			if(!error.value){
				console.log("User Log out")
        router.push('/')
			}
		}
    watch(user,()=>{
			if(!user.value){
				router.push('/')
			}
		});

		return {
			handleClick, user
		}
	},
};
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap");
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
main {
  color: white;
  font-family: "Ubuntu";
  font-style: normal;
  font-weight: bold;
  font-size: 16px;
  background-color: #303841;
  min-height: 100vh;
}
main > section {
  display: block;
  align-items: center;
  padding: 2rem 10rem 2rem 10rem;
}
div.layout {
  height: auto;
  margin-top: 2rem;
}
div#user_inform {
  margin: 0;
}
div#information {
  display: flex;
  align-items: center;
}
div#information .icon-user {
  font-size: 20px;
  margin-right: 1rem;
}
div#information .icon-email {
  font-size: 20px;
  margin-right: 1rem;
}
div.layout div.title {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-bottom: 15px;
  border-bottom: white solid 2px;
  margin-bottom: 2rem;
}
div#user_inform button {
  padding: 10px 20px 10px 20px;
  background: var(--primary-color);
  border: none;
  border-radius: 50px;
  font-weight: bolder;
  color: white;
  cursor: pointer;
}
.addcard-btn {
  padding: 5px 10px 5px 10px;
  background: var(--primary-color);
  border: none;
  border-radius: 30px;
  font-weight: bolder;
  color: white;
  cursor: pointer;
}
div.item_buy {
  height: 15rem;
  margin-top: 3rem;
  align-items: flex-end;
  display: flex;
  justify-content: space-between;
}

div.item_buy ul {
  list-style: none;
  padding-left: 2rem;
}

</style>